update the version

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,6 +27,11 @@ jobs:
 
       - name: Build artifact
         run: make build
+        
+      - name: 🧾 Show bin directory contents
+        run: |
+          echo "Checking build output:"
+          ls -lh bin || echo "❌ bin/ not found"
 
       - name: Upload binary
         uses: actions/upload-artifact@v4
